-- profilesテーブルを作成
-- Supabaseの認証ユーザーと自動的に連携されます
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text
);

-- revealsテーブルを作成
create table public.reveals (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles not null,
  template_id text not null,
  gender text not null,
  share_slug text not null unique,
  is_paid boolean default false not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);